<?php
require_once "class.eval.inc";
require_once "class.courses.inc";
require_once "class.grades.inc";
require_once "class.housing.inc";
require_once "class.mails.inc";
require_once "class.password.inc";
require_once "class.reidhall.inc";
require_once "class.stage.inc";
require_once "class.student.inc";
require_once "class.univ.inc";
require_once "class.univ_reg.inc";
require_once "class.users.inc";
require_once "phpmailer/class.phpmailer.php";
?>
