<?php
// require_once "class.courses.inc";
// 
// 
// class schedule{
//   public $student=null;
//   public $semester=null;
// 
//   public function schedule(){
//     $this->student=$_SESSION['vwpp']['std-id']?$_SESSION['vwpp']['std-id']:$_SESSION['vwpp']['student'];
//     $this->semester=str_replace(" ","_",$_SESSION['vwpp']['semester']);
//   }
// 
//   public function get(){
//     $c=new courses();
//     $c->fetch($this->student);
//     print_r($c->vwpp_courses);
// 
//     echo "<br><br>";
//     print_r($c->univ_courses);
//     echo "<br><br>";
// 
//     print_r($c->ciph_courses);
//   }
// 
// 
// }


?>