<?php
// Update : 2015-11-14
global $lang;
$lang=array(
  "update_success"=> "Update successful",
  "update_error"=> "Error while updating",
  "insert_success"=> "Update successful",
  "insert_error"=> "Error while updating",
  "delete_success"=> "Delete successful",
  "delete_error"=> "Error while deleting",
  "deleteTIN_success"=> "TIN deleted successfully",
  "deleteTIN_error"=> "Error while deleting TIN",
  "send_email_success"=> "E-mail sent successful",
  "send_emails_success"=> "E-mails sent successful",
  "send_email_error"=> "Error while sending E-mail",
  "send_emails_error"=> "Error while sending E-mails",
  "wrong_current_password"=> "Wrong current password",
  "passwords_dont_match"=> "Passwords don't match",
  "password_too_short"=> "New password is too short",
  "change_password_error"=> "Error while updating password",
  "change_password_success"=> "Update password successful",
  "accept_charte"=> "You must accept the charte",
  "lock_success"=> "Lock successful",
  "unlock_success"=> "Unlock successful",
  "upload_success"=>"Upload successful",
  "upload_erro"=>"Error while upload",
  "access_denied"=>"Access Denied"
);

?>