<?php
// 2015-11-14

$lang["update_success"]="Mise à jour réussie";
$lang["update_error"]="La mise à jour a échoué";
$lang["insert_success"]="Informations enregistrées";
$lang["insert_error"]="La mise à jour a échoué";
$lang["delete_success"]="Suppression réussie";
$lang["delete_error"]="Erreur lors de la suppression";
$lang["deleteTIN_success"=> "TIN supprimé avec succés";
$lang["deleteTIN_error"=> "Erreur lors de la suppression du TIN";
$lang["send_email_success"]="Le mail a bien été envoyé";
$lang["send_emails_success"]="Les mails ont bien été envoyés";
$lang["wrong_current_password"]="Mot de passe actuel incorrect";
$lang["passwords_dont_match"]="Les mots de passe ne correspondent pas";
$lang["password_too_short"]="Nouveau mot de passe trop court";
$lang["change_password_error"]="La mise à jour du mot de passe a échoué";
$lang["change_password_success"]="Le mot de passe a bien été modifié";
$lang["accept_charte"]="Vous devez accepter la charte";
$lang["lock_success"]="Vérrouillage réussi";
$lang["unlock_success"]="Déverrouillage réussi";
$lang["upload_success"]="Upload successful";
$lang["upload_error"]="Error while upload";
$lang["access_denied"]="Accès refusé";

?>
