<?php
require_once "../inc/config.php";


$tab[]=array("167","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Histoire de l'Art","Art History","L2","L4AA10","Histoire de l'Art de XIXème-XXème","Art History of the 19th-20th Centuries","M.A Goetz","M.A Goetz");
$tab[]=array("212","UP3","Arts et Médias","Arts and Media","Cinéma et théâtre","Cinema and Theatre","Cinema et audiovisuel","Cinema and audiovisual","L2","V4FF1","France/Hollywood: une approche culturelle des échanges cinématographiques","France/Hollywood: a Cultural Approach to Cinematographic Exchange","Raphaelle Moine","");
$tab[]=array("212","UP3","Littérature, Linguistique et Didactique","Literature, Linguistics and Didactics","Professorat des écoles","School Teaching","Littérature et Linguistique Françaises et Latines","French and Romance literature and linguistics","L3","F6130","Littérature de Jeunesse","Young-Adult Literature","B. Milland-Bove","");
$tab[]=array("136","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Archéologie / Histoire de l'Art","History of Art and Archeology","L2","L4AA08","Histoire des arts de la Renaissance","History of Art of the Renaissance","Lurin","Lurin");
$tab[]=array("136","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Archéologie / Histoire de l'Art","History of Art and Archeology","L2","L4AA11","L'Art et les Avant-Gardes (Histoire de l'Art du XX-XXIème siècle)","Art and the Avant-gardes (Art History of the 20th-21st Centuries)","Maillet","Mme A. Simoniello");
$tab[]=array("137","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Histoire Ancienne","Ancient History","Histoire","History","L2","54U1HH24","Ancienne 2: De la fondation de Rome aux guerres puniques","Ancient History: From the Foundation of Rome to the Punic Wars","S. Wyler","A.C. Michel");
$tab[]=array("165","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Histoire de l'Art","Art History","L2","L4AA10","Histoire de l'Art de XIXème-XXème","Art History of the 19th-20th Centuries","M.A Goetz","M.A Goetz");
$tab[]=array("138","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Economie-Gestion","Economy - Management","Sciences Économiques et Sociales (SES)","Economics and Social Sciences","L2","54EC2054","Économie du Travail","Labor Economics","M-J Voisin","Saiag");
$tab[]=array("139","UP7","Sciences Sociales","Social Studies","Histoire et neurobiologie","History and Neurobiology","Psychologie","Psychology","L2","45LP5224","Neurobiologie Cognitive","Cognitive Neurobiology","Maier Marc","");
$tab[]=array("139","UP7","Sciences Sociales","Social Studies","Sociologie","Sociology","Sociologie","Sociology","L2","54SO1224","Sociologie de l'école","Sociology of the School","C. Poiret","Beunardeau");
$tab[]=array("153","UP3","Arts et Médias","Arts and Media","Études cinématographiques et audiovisuel","Cinema and Audiovisual Studies","Cinéma et audiovisuel","Cinema and audiovisual","L3","V6F01"," Esthétique du Cinéma et de l'Audiovisuel (Mise en scène de la sexualité chez les cinéastes contemporains)","Aesthetics of Cinema  (Filming Sexuality by Contemporary Filmmakers)","","Hélène FLECKINGER");
$tab[]=array("153","UP3","Arts et Médias","Arts and Media","Études cinématographiques et audiovisuel","Cinema and Audiovisual Studies","Cinéma et audiovisuel","Cinema and audiovisual","L3","V6FF3","Le Cinéma Allemand Contemporain","Contemporary German Cinema","","Matthias STEINLE ");
$tab[]=array("140","UP7","Lettres, Arts et Cinéma","Humanities, Arts and Cinema","Lettres et Arts","Arts","Lettres","Humanities","L2","54HL2114","Humanités","Humanities","Jean-François Guennoc","");
$tab[]=array("150","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Histoire de l'Art","Art History","L2","L4AA10","Histoire de l'Art de XIXème-XXème","Art History of the 19th-20th Centuries","M.A Goetz","M.A Goetz");
$tab[]=array("150","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Archéologie / Histoire de l'Art","History of Art and Archeology","L2","L4AA08","Histoire des arts de la Renaissance","History of Art of the Renaissance","Lurin","Lurin");
$tab[]=array("141","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Economie-Gestion","Economy - Management","Sciences Économiques et Sociales (SES)","Economics and Social Sciences","L2","54EC2054","Économie du Travail","Labor Economics","M-J Voisin","Saiag");
$tab[]=array("142","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Économie-Gestion","Economy - Management","Sciences Économiques et Sociales","Economics and Social Sciences","L1","54EC1042","Comptabilité gestion: comptabilité générale","Accounting and Management: General Accounting","Duard","Duard (femme)");
$tab[]=array("142","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Économie-Gestion","Economy - Management","Sciences Économiques et Sociales","Economics and Social Sciences","L2","54EC2054","Économie du travail","Labor Economics","M-J Voisin","Saiag");
$tab[]=array("154","UP7","Sciences Sociales","Social Studies","Sociologie","Sociology","Sociologie - Anthropologie","Sociology - Anthropology","L3","47LS3046","Genre et Sciences Sociales","Gender and Social Science","Nathalie Puvilland","");
$tab[]=array("154","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Histoire","History","Histoire","History","L3","43HI4936","Les Religions de Rome: textes, images et archéologie","Religions of Rome: Texts, Images and Archaeology","S. Wyler","");
$tab[]=array("155","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Archéologie / Histoire de l'Art","History of Art and Archeology","L2","L4AA08","Histoire des arts de la Renaissance","History of Art of the Renaissance","Lurin","Lurin");
$tab[]=array("155","UP4","Archéologie / Histoire de l'Art","History of Art and Archeology","Histoire de l'Art","Art History","Archéologie / Histoire de l'Art","History of Art and Archeology","L2","L4AA11","L'Art et les Avant-Gardes (Histoire de l'Art du XX-XXIème siècle)","Art and the Avant-gardes (Art History of the 20th-21st Centuries)","Monsieur Maillet","Mme A. Simoniello");
$tab[]=array("156","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Parcours général de géographie","General Stream of Geography","Géographie","Georgraphy","L3","43GO3186","Géographie Historique","Historical Geography","Christian Grataloup","");
$tab[]=array("156","UP7","Lettres, Arts et Cinéma","Humanities, Arts and Cinema","Enseignements artistiques théoriques","Art Theory ","Études cinématographiques","Cinema Studies","L2","54CI2174","Le cinéma hollywoodien 1972 - 2005","Hollywood Cinema from 1972 to 2005","P. Berthomieu","");
$tab[]=array("143","UP3","Arts et Médias","Arts and Media","Cinéma et théâtre","Cinema and Theatre","Cinema et audiovisuel","Cinema and audiovisual","L2","V4FF1","Les archétypes socioculturels au cinéma du savant fou au faux coupable","Sociocultural Archetypes in Cinema, from The Mad-Doctor to The Wrong Man","Chloë Delaporte","");
$tab[]=array("143","UP3","Langues, Littératures, Cultures et Sociétés Étrangères (LLCSE)","Langages, Literatures, Cultures and Foreign Societies","Culture, enseignement, recherche","Culture, Education, Research","Etudes Arabes, Hébraiques, Indiennes","Arabic, Hebraic and Indian studies","L2","O4A32","Sociologie culturelle du monde arabe","Cultural Sociology of the Arab World","","Mme Hamda");
$tab[]=array("144","UP7","Sciences du Vivant","Natural and Life Sciences","Vie et Terre","Earth and Life Sciences","Sciences de la Nature et de la Vie","Natural and Life sciences","L2","52U6PT24","Panorama des Sciences de la Terre moderners 2","Panorama of Modern Earth Science 2","Frédéric Fluteau","Frédéric Fluteau");
$tab[]=array("145","UP7","Lettres, Arts et Cinéma","Humanities, Arts and Cinema","Lettres et Arts","Arts and Humanities","Lettres","Humanities","L2","46COCW36","Atelier d'écriture créative","Workshop on Creative Writting","J-F Guennoc","");
$tab[]=array("145","UP7","Sciences Sociales","Social Studies","Histoire et neurobiologie","History and Neurobiology","Psychologie","Psychology","L3","45LP2136","Lecture:  Psychologie clinique: psychologie du traumatisme / Discussion: Études de textes en psychologie du traumatisme 3","Lecture: Clinical Pychology: Pychology of Trauma / Discussion: Studies of Texts on the Psychology of Trauma 3","Rémy Potier","Atmani Isabelle");
$tab[]=array("145","UP7","Sciences Sociales","Social Studies","Psychosociologie","Psychosociology","Sociologie","Sociology","L2","54PS1284","Psychosociologie ","Psychosociology","C. Lecompte","");
$tab[]=array("157","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Economie-Gestion","Economy - Management","Département des Lettres et Sciences Humaines (LSH)","Department of Humanities and Social Sciences","L1","54EC2034","Economie de l'Environnement","Economy of the Environment ","E. Magnin","Florent Gabriel");
$tab[]=array("157","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Economie-Gestion","Economy - Management","Département des Lettres et Sciences Humaines (LSH)","Department of Humanities and Social Sciences","L2","54EC2064","Monnaie","Currency","Rubinstein","Sepot");
$tab[]=array("146","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Economie-Gestion","Economy - Management","Département des Lettres et Sciences Humaines (LSH)","Department of Humanities and Social Sciences","L2","54EC2014","Économie de la protection","Welfare Economics","M-J Voisin","M-J Voisin");
$tab[]=array("146","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Économie-Gestion","Economy - Management","Département des Lettres et Sciences Humaines (LSH)","Department of Humanities and Social Sciences","L2","54EC2054","Économie du Travail","Labor Economics","Voisin","Saiag");
$tab[]=array("147","UP3","Arts et Médias","Arts and Media","Cinéma et théâtre","Cinema and Theatre","Cinéma et audiovisuel","Cinema and audiovisual","L2","V4FF1","France/Hollywood: une approche culturelle des échanges cinématographiques","France/Hollywood: a Cultural Approach to Cinematographic Exchange","","Raphaëlle Moine");
$tab[]=array("147","UP3","Littérature, Linguistique et Didactique","Literature, Linguistics and Didactics","Littérature","Literature","Littérature et Linguistique Françaises et Latines","French and Latin literature and linguistics","L3","F6130","Littérature de Jeunesse","Young-Adult Literature","Benedicte Milland-Bove","");
$tab[]=array("158","UP7","Sciences Sociales","Social Studies","Sociologie","Sociology","Sociologie","Sociology","L2","54S02504","Sociologie contemporaine","Contemporary Sociology","D. Merklen","D. Merklen");
$tab[]=array("158","UP7","Sciences Sociales","Social Studies","Sociologie","Sociology","Sociologie","Sociology","L2","54SO1224","Sociologie de l'école","Sociology of the School","C. Poiret","N. Puvilland");
$tab[]=array("168","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Histoire","History","Histoire","History","L3","43HI2136","Histoire des Sensibilités","History of Sensitivity","A-E De Martini","");
$tab[]=array("168","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Histoire","History","Histoire","History","L3","43HI4936","Les Religions de Rome: textes, images et archéologie","Religions of Rome: Texts, Images and Archaeology","S. Wyler","");
$tab[]=array("151","UP3","Littérature, Linguistique et Didactique","Literature, Linguistics and Didactics","Littérature","Literature","Littérature et Linguistique Françaises et Latines","French and Latin literature and linguistics","L2","F4142","Littérature et Histoire: XVIème siècle. Une écriture à vif: témoigner des Guerres de religion","Literature and History: 16th Century: a Vivid Writing: Chronicling the  Wars of Religion","","Nathalie Dauvois");
$tab[]=array("151","UP3","Langues, Littératures, Cultures et Sociétés Étrangères (LLCSE)","Langages, Literatures, Cultures and Foreign Societies","Culture, enseignement, recherche","Culture, Education, Research","Études Arabes, Hébraïques, Indiennes et Iraniennes","Arabic, Hebraic and Indian studies","L2","O4A32","Sociologie culturelle du monde arabe","Cultural Sociology of the Arab World","Mme Hamda","");
$tab[]=array("148","UP3","Arts et Médias","Arts and Media","Cinéma et théâtre","Cinema and Theatre","Cinéma et audiovisuel","Cinema and audiovisual","L2","V4FF1","Les archétypes socioculturels au cinéma du savant fou au faux coupable","Sociocultural Archetypes in Cinema, from The Mad-Doctor to The Wrong Man","Chloë Delaporte","");
$tab[]=array("148","UP3","Langues, Littératures, Cultures et Sociétés Étrangères (LLCSE)","Langages, Literatures, Cultures and Foreign Societies","Culture, enseignement, recherche","Culture, Education, Research","Études Arabes, Hébraïques, Indiennes et Iraniennes","Arabic, Hebraic and Indian studies","L3","O4A32","Sociologie culturelle du monde arabe","Cultural Sociology of the Arab World","Mme Hamda","");
$tab[]=array("166","UP7","LANSAD","Languages for Specialists of Other Subjects","Allemand","German","LANSAD","Languages for specialists of other disciplines","L2","","Allemand: Langue, Culture et Civilisation","German: Language, Culture and Civilization","Christian Reuter","");
$tab[]=array("166","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Histoire","History","Histoire","History","L2","54HI2234","Amérique latine / Monde Ibérique","Latin America / The Iberian World","","M. Moutoukias (et A. Gonzalez)");
$tab[]=array("160","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Histoire","History","Histoire","History","L2","54HI2344","Histoire de l'Europe au XIXème siècle - Aspects politiques 2","History of Europe in the 19th Century - Political Aspects 2","A-E De Martini","K. Salome");
$tab[]=array("149","UP7","Géographie, Histoire, Sciences de la Société (GHSS)","Geography, History and Sciences of Society","Economie-Gestion","Economy - Management","Département des Lettres et Sciences Humaines (LSH)","Department of Humanities and Social Sciences","L2","54EC2054","Économie du travail","Labor Economics","Voisin","Saiag");

/*
","University","UFR","UFR name","Parcours ","Stream","Département","Department","Course year (L1 / L2 / L3)","Course code","Nom du cours","Course title","Lecture Course Instructor","Discussion section Instructor");
*/



$db=new dbh();
$db->prepare("insert into courses_univ (student,semester,university,ufr,ufr_en,parcours,parcours_en,departement,departement_en,niveau,cm_code,cm_name,cm_name_en,cm_prof,td_prof) 
values 
(:student,:semester,:university,:ufr,:ufr_en,:parcours,:parcours_en,:departement,:departement_en,:niveau,:cm_code,:cm_name,:cm_name_en,:cm_prof,:td_prof);");

foreach($tab as $elem){
	$insert=array(":student"=>$elem[0],":semester"=>"Spring_2012",":university"=>encrypt($elem[1],$elem[0]),":ufr"=>encrypt($elem[2],$elem[0]),":ufr_en"=>encrypt($elem[3],$elem[0]),":parcours"=>encrypt($elem[4],$elem[0]),":parcours_en"=>encrypt($elem[5],$elem[0]),":departement"=>encrypt($elem[6],$elem[0]),":departement_en"=>encrypt($elem[7],$elem[0]),":niveau"=>encrypt($elem[8],$elem[0]),":cm_code"=>encrypt($elem[9],$elem[0]),":cm_name"=>encrypt($elem[10],$elem[0]),":cm_name_en"=>encrypt($elem[11],$elem[0]),":cm_prof"=>encrypt($elem[12],$elem[0]),":td_prof"=>encrypt($elem[13],$elem[0]));
	$db->execute($insert);

}

?>
